services:
  - type: web
    name: disaster-monitor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: WEATHERAPI_KEY
        sync: false
      - key: AMBEE_API_KEY
        sync: false